[build]
  command = "pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  PNPM_FLAGS = "--no-frozen-lockfile"
  NEXT_SHARP_PATH = "/opt/build/repo/node_modules/sharp"

[build.processing]
  skip_processing = false